import type { SalesOffice } from '../types/salesoffice';

export const _salesOfficeList: SalesOffice[] = [
  {
    // Identification
    id: '1',
    officeCode: 'SO-NYC-001',
    name: 'New York Downtown Sales Office',
    officeType: 'headquarters',

    // Visual Identity
    logo: '/assets/images/offices/nyc-logo.png',
    coverImage: '/assets/images/offices/nyc-cover.jpg',
    
    // Contact Information
    email: 'nyc.sales@company.com',
    phoneNumber: '+1-212-555-0101',
    alternatePhone: '+1-212-555-0102',
    website: 'https://nyc.company.com',

    // Location Information
    address: '123 Broadway Avenue',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    zipCode: '10001',
    timezone: 'America/New_York',
    
    // Key Personnel
    officeManager: 'user-001',
    officeManagerName: 'Sarah Johnson',
    regionalDirector: 'Michael Chen',
    salesTeamLead: 'John Doe',
    supportStaffContact: 'Jane Smith',
    
    // Office Information
    companyId: 'comp-001',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2015,
    totalEmployees: 25,
    officeSize: 'Large',
    facilities: ['Meeting Rooms', 'Parking', 'Cafeteria'],
    
    // Operational Information
    operatingHours: {
      weekdays: '9:00 AM - 6:00 PM',
      saturday: '10:00 AM - 4:00 PM',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales', 'Consulting', 'Support'],
    targetRegions: ['Northeast'],
    
    // Status & Metadata
    status: 'active',
    isVerified: true,
    tags: ['premium', 'downtown'],
    notes: 'Main headquarters office',
    
    // Timestamps
    createdAt: new Date('2015-03-10'),
    updatedAt: new Date('2024-01-15'),
    lastActivityAt: new Date('2024-01-15')
  },
  {
    id: '2',
    officeCode: 'SO-LA-002',
    name: 'Los Angeles West Coast Office',
    officeType: 'regional',
    logo: '/assets/images/offices/la-logo.png',
    email: 'la.sales@company.com',
    phoneNumber: '+1-310-555-0202',
    address: '456 Sunset Boulevard',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    zipCode: '90210',
    timezone: 'America/Los_Angeles',
    officeManager: 'user-002',
    officeManagerName: 'David Rodriguez',
    regionalDirector: 'Michael Chen',
    salesTeamLead: 'Mike Johnson',
    supportStaffContact: 'Sarah Wilson',
    companyId: 'comp-002',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2018,
    totalEmployees: 18,
    officeSize: 'Medium',
    facilities: ['Meeting Rooms', 'Parking'],
    operatingHours: {
      weekdays: '9:00 AM - 6:00 PM',
      saturday: '10:00 AM - 4:00 PM',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales', 'Consulting'],
    targetRegions: ['West Coast'],
    status: 'active',
    isVerified: true,
    tags: ['west-coast', 'regional'],
    notes: 'West coast regional office',
    createdAt: new Date('2018-06-15'),
    updatedAt: new Date('2024-01-10'),
    lastActivityAt: new Date('2024-01-12')
  },
  {
    id: '3',
    officeCode: 'SO-CHI-003',
    name: 'Chicago Midwest Regional Office',
    officeType: 'regional',
    logo: '/assets/images/offices/chicago-logo.png',
    coverImage: '/assets/images/offices/chicago-cover.jpg',
    email: 'chicago.sales@company.com',
    phoneNumber: '+1-312-555-0303',
    alternatePhone: '+1-312-555-0304',
    website: 'https://chicago.company.com',
    address: '789 Michigan Avenue',
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    zipCode: '60601',
    timezone: 'America/Chicago',
    officeManager: 'user-003',
    officeManagerName: 'Emily Watson',
    regionalDirector: 'Jennifer Kim',
    salesTeamLead: 'Robert Brown',
    supportStaffContact: 'Lisa Taylor',
    companyId: 'comp-003',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2016,
    totalEmployees: 15,
    officeSize: 'Medium',
    facilities: ['Meeting Rooms'],
    operatingHours: {
      weekdays: '9:00 AM - 6:00 PM',
      saturday: '10:00 AM - 2:00 PM',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales', 'Support'],
    targetRegions: ['Midwest'],
    status: 'inactive',
    isVerified: true,
    tags: ['midwest', 'regional'],
    notes: 'Currently under renovation',
    createdAt: new Date('2016-08-22'),
    updatedAt: new Date('2024-01-08'),
    lastActivityAt: new Date('2024-01-05')
  },
  {
    id: '4',
    officeCode: 'SO-MIA-004',
    name: 'Miami Beachfront Sales Office',
    officeType: 'branch',
    email: 'miami.sales@company.com',
    phoneNumber: '+1-305-555-0404',
    address: '321 Ocean Drive',
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    zipCode: '33139',
    timezone: 'America/New_York',
    officeManager: 'user-004',
    officeManagerName: 'Carlos Martinez',
    regionalDirector: 'Jennifer Kim',
    salesTeamLead: 'Maria Garcia',
    supportStaffContact: 'David Lee',
    companyId: 'comp-004',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2020,
    totalEmployees: 12,
    officeSize: 'Small',
    facilities: ['Meeting Room'],
    operatingHours: {
      weekdays: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales'],
    targetRegions: ['Southeast'],
    status: 'pending',
    isVerified: false,
    tags: ['beachfront', 'new'],
    notes: 'New office setup in progress',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-03'),
    lastActivityAt: new Date('2024-01-02')
  },
  {
    id: '5',
    officeCode: 'SO-SEA-005',
    name: 'Seattle Pacific Northwest Office',
    officeType: 'branch',
    logo: '/assets/images/offices/seattle-logo.png',
    email: 'seattle.sales@company.com',
    phoneNumber: '+1-206-555-0505',
    address: '654 Pine Street',
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    zipCode: '98101',
    timezone: 'America/Los_Angeles',
    officeManager: 'user-005',
    officeManagerName: 'Robert Wilson',
    regionalDirector: 'Michael Chen',
    salesTeamLead: 'Jennifer Adams',
    supportStaffContact: 'Thomas Clark',
    companyId: 'comp-005',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2019,
    totalEmployees: 10,
    officeSize: 'Small',
    facilities: ['Meeting Room'],
    operatingHours: {
      weekdays: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales'],
    targetRegions: ['Pacific Northwest'],
    status: 'closed',
    isVerified: true,
    tags: ['pacific', 'closed'],
    notes: 'Office closed due to restructuring',
    createdAt: new Date('2019-04-10'),
    updatedAt: new Date('2023-12-15'),
    lastActivityAt: new Date('2023-11-20')
  },
  {
    id: '6',
    officeCode: 'SO-AUS-006',
    name: 'Austin Texas Regional Office',
    officeType: 'regional',
    logo: '/assets/images/offices/austin-logo.png',
    email: 'austin.sales@company.com',
    phoneNumber: '+1-512-555-0606',
    address: '987 Congress Avenue',
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    zipCode: '78701',
    timezone: 'America/Chicago',
    officeManagerName: 'Lisa Thompson',
    regionalDirector: 'Jennifer Kim',
    salesTeamLead: 'Brian Davis',
    supportStaffContact: 'Amanda White',
    companyId: 'comp-001',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2023,
    totalEmployees: 8,
    officeSize: 'Small',
    facilities: ['Meeting Room'],
    operatingHours: {
      weekdays: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales', 'Consulting'],
    targetRegions: ['Southwest'],
    status: 'under-construction',
    isVerified: false,
    tags: ['texas', 'construction'],
    notes: 'Office under construction',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2024-01-01'),
    lastActivityAt: new Date('2023-12-28')
  },
  {
    id: '7',
    officeCode: 'SO-BOS-007',
    name: 'Boston New England Sales Office',
    officeType: 'regional',
    logo: '/assets/images/offices/boston-logo.png',
    coverImage: '/assets/images/offices/boston-cover.jpg',
    email: 'boston.sales@company.com',
    phoneNumber: '+1-617-555-0707',
    alternatePhone: '+1-617-555-0708',
    website: 'https://boston.company.com',
    address: '147 Beacon Street',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    zipCode: '02108',
    timezone: 'America/New_York',
    officeManager: 'user-007',
    officeManagerName: 'Thomas Anderson',
    regionalDirector: 'Michael Chen',
    salesTeamLead: 'Jessica Miller',
    supportStaffContact: 'Kevin Wilson',
    companyId: 'comp-002',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2017,
    totalEmployees: 20,
    officeSize: 'Medium',
    facilities: ['Meeting Rooms', 'Parking'],
    operatingHours: {
      weekdays: '9:00 AM - 6:00 PM',
      saturday: '10:00 AM - 4:00 PM',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales', 'Consulting', 'Training'],
    targetRegions: ['New England'],
    status: 'active',
    isVerified: true,
    tags: ['boston', 'new-england'],
    notes: 'New England regional headquarters',
    createdAt: new Date('2017-02-14'),
    updatedAt: new Date('2024-01-14'),
    lastActivityAt: new Date('2024-01-13')
  },
  {
    id: '8',
    officeCode: 'SO-DEN-008',
    name: 'Denver Mountain Region Office',
    officeType: 'branch',
    email: 'denver.sales@company.com',
    phoneNumber: '+1-303-555-0808',
    address: '258 Colfax Avenue',
    city: 'Denver',
    state: 'CO',
    country: 'USA',
    zipCode: '80202',
    timezone: 'America/Denver',
    officeManager: 'user-008',
    officeManagerName: 'Amanda Lee',
    regionalDirector: 'Jennifer Kim',
    salesTeamLead: 'Daniel Moore',
    supportStaffContact: 'Rachel Scott',
    companyId: 'comp-003',
    companyName: 'Premium Real Estate Group',
    establishedYear: 2021,
    totalEmployees: 14,
    officeSize: 'Small',
    facilities: ['Meeting Room', 'Parking'],
    operatingHours: {
      weekdays: '9:00 AM - 5:00 PM',
      saturday: 'Closed',
      sunday: 'Closed'
    },
    servicesOffered: ['Sales'],
    targetRegions: ['Mountain Region'],
    status: 'pending',
    isVerified: false,
    tags: ['denver', 'mountain'],
    notes: 'Pending final approval',
    createdAt: new Date('2021-11-30'),
    updatedAt: new Date('2024-01-07'),
    lastActivityAt: new Date('2024-01-06')
  }
];